-- Insert sample courses into Supabase
-- Run this in Supabase SQL Editor

INSERT INTO courses (title, slug, icon, level, duration, students, rating, price, short_desc, description, what_you_learn, modules, outcomes, image, popular, featured) VALUES
('Social Media Management', 'social-media', 'FaBullhorn', 'Beginner', '8 weeks', '250+', 4.9, '$299', 'Help brands grow their online presence across all platforms.', 'Master the art of managing social media accounts for businesses.', '["Create engaging content calendars","Grow organic following strategically","Use analytics to optimize performance","Manage multiple client accounts","Create viral-worthy content","Build brand voice and identity"]', '[{"title":"Foundation of Social Media","lessons":5},{"title":"Content Creation & Strategy","lessons":8},{"title":"Community Management","lessons":4},{"title":"Analytics & Reporting","lessons":6},{"title":"Client Management","lessons":4},{"title":"Building Your Portfolio","lessons":3}]', '["Manage 3-5 client accounts","Earn $1,500-$3,000 per client monthly","Build a professional portfolio","Get certified and job-ready"]', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=500&fit=crop', true, false),

('Facebook & Instagram Ads', 'facebook-ads', 'FaFacebook', 'Beginner', '6 weeks', '180+', 4.8, '$349', 'Master Meta ads to drive sales and conversions for businesses.', 'Become a certified Meta ads specialist.', '["Set up Meta Business Manager","Create high-converting ad creatives","Target the perfect audience","Optimize ad spend for maximum ROI","A/B test ads effectively","Track and report campaign performance"]', '[{"title":"Meta Ads Foundation","lessons":4},{"title":"Audience Targeting Mastery","lessons":6},{"title":"Ad Creative & Copywriting","lessons":5},{"title":"Campaign Optimization","lessons":6},{"title":"Retargeting Strategies","lessons":4},{"title":"Scaling & Reporting","lessons":3}]', '["Run profitable ad campaigns","Charge $500-$2,000 per setup","Manage monthly ad budgets","Get Meta certified"]', 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=800&h=500&fit=crop', false, false),

('TikTok Ads', 'tiktok-ads', 'FaTiktok', 'Beginner', '4 weeks', '120+', 4.7, '$249', 'Tap into the fastest-growing platform for viral marketing.', 'Learn to create and manage TikTok ad campaigns that go viral.', '["Understand TikTok algorithm","Create viral ad content","Use TikTok Ads Manager","Leverage trending sounds and effects","Target Gen Z and Millennial audiences","Measure campaign success"]', '[{"title":"TikTok Platform Basics","lessons":3},{"title":"Viral Content Creation","lessons":6},{"title":"TikTok Ads Manager","lessons":5},{"title":"Trend Marketing","lessons":4}]', '["Create viral TikTok ads","Earn $1,000-$2,500 per campaign","Work with e-commerce brands","Build a TikTok portfolio"]', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=800&h=500&fit=crop', true, false),

('Digital Marketing', 'digital-marketing', 'FaBullhorn', 'All Levels', '10 weeks', '300+', 4.9, '$499', 'Learn complete online sales funnels and marketing strategies.', 'Become a full-stack digital marketer.', '["SEO and content marketing","Email marketing automation","Sales funnel creation","Multi-channel marketing","Google Analytics mastery","Marketing strategy development"]', '[{"title":"Digital Marketing Fundamentals","lessons":6},{"title":"SEO Mastery","lessons":8},{"title":"Email Marketing","lessons":5},{"title":"Paid Advertising","lessons":7},{"title":"Analytics & Data","lessons":6},{"title":"Strategy & Planning","lessons":4}]', '["Work as marketing manager","Earn $3,000-$6,000 monthly","Handle complete marketing","Start your own agency"]', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop', false, false),

('Virtual Assistant', 'virtual-assistant', 'FaEnvelope', 'Beginner', '8 weeks', '200+', 4.8, '$279', 'Provide remote administrative and creative support to executives.', 'Launch your career as a professional virtual assistant.', '["Essential VA tools and software","Email and calendar management","Client communication skills","Time management & productivity","Travel planning & booking","Basic bookkeeping"]', '[{"title":"VA Fundamentals","lessons":5},{"title":"Tools & Software","lessons":6},{"title":"Communication Mastery","lessons":4},{"title":"Task Management","lessons":5},{"title":"Client Relations","lessons":4},{"title":"Finding Clients","lessons":3}]', '["Work with international clients","Earn $15-$40 per hour","Flexible remote work","Build long-term contracts"]', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=500&fit=crop', false, false),

('Graphic Design', 'graphic-design', 'FaPenNib', 'Beginner', '10 weeks', '220+', 4.9, '$399', 'Master graphic design from scratch. Learn Adobe Photoshop, Illustrator, and Canva.', 'Create logos, social media graphics, marketing materials, and brand identities that stand out.', '["Design principles & typography","Adobe Photoshop mastery","Adobe Illustrator essentials","Brand identity design","Social media graphics","Client presentation skills"]', '[{"title":"Design Fundamentals","lessons":6},{"title":"Photoshop Mastery","lessons":8},{"title":"Illustrator Essentials","lessons":7},{"title":"Brand Identity","lessons":5},{"title":"Marketing Materials","lessons":4},{"title":"Building Portfolio","lessons":4}]', '["Create professional designs","Charge $50-$500 per project","Build design portfolio","Work with global clients"]', 'https://images.unsplash.com/photo-1626785774573-4b799314346d?w=800&h=500&fit=crop', true, false),

('WhatsApp Marketing', 'whatsapp-marketing', 'FaWhatsapp', 'Beginner', '4 weeks', '150+', 4.6, '$199', 'Help businesses sell directly through WhatsApp conversations.', 'Learn the power of conversational marketing.', '["WhatsApp Business setup","Broadcast list strategies","Automated message sequences","Customer relationship management","Sales conversation techniques","Compliance and best practices"]', '[{"title":"WhatsApp Business Basics","lessons":3},{"title":"Building Contact Lists","lessons":4},{"title":"Message Automation","lessons":5},{"title":"Sales Through WhatsApp","lessons":4}]', '["Help businesses sell via WhatsApp","Earn $500-$1,500 per client","Set up WhatsApp systems","Work with local businesses"]', 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=800&h=500&fit=crop', false, false),

('Video Editing', 'video-editing', 'FaVideo', 'Beginner', '8 weeks', '190+', 4.8, '$379', 'Edit engaging content for creators, brands, and social media.', 'Become a professional video editor.', '["Video editing fundamentals","Adobe Premiere Pro mastery","Color grading & correction","Audio editing & mixing","Motion graphics basics","Export optimization"]', '[{"title":"Editing Fundamentals","lessons":5},{"title":"Premiere Pro Mastery","lessons":8},{"title":"Color Grading","lessons":5},{"title":"Audio Editing","lessons":4},{"title":"Motion Graphics","lessons":4},{"title":"Portfolio Projects","lessons":4}]', '["Edit professional videos","Earn $100-$500 per video","Work with YouTubers & brands","Freelance or full-time roles"]', 'https://images.unsplash.com/photo-1574717432707-c5719b277e44?w=800&h=500&fit=crop', true, false);
