services:
  - type: web
    name: juju-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/courses
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: juju-secret-key-2026
      - key: PORT
        value: 5001
